<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia.Desktop" Version="12.1.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Tinysnap.App\Tinysnap.App.csproj" />
  </ItemGroup>

</Project>
